global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ape-load-test'
    environment: 'development'

rule_files:
  - "rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      # Add custom labels for APE services
      - source_labels: [container_label_com_docker_compose_service]
        target_label: ape_service
      - source_labels: [container_label_com_docker_compose_project]
        target_label: ape_project
      # Rename container name for clarity
      - source_labels: [name]
        regex: '/(.*)'
        target_label: container_name

  # Node Exporter for host system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # APE Agent custom metrics (dynamic discovery)
  - job_name: 'ape-agents'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 8000
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.compose.service=llama-agent"]
    relabel_configs:
      # Only scrape containers with metrics port exposed
      - source_labels: [__meta_docker_port_public]
        regex: '8000'
        action: keep
      # Set job label
      - target_label: job
        replacement: 'ape-agent'
      # Extract agent ID from container name
      - source_labels: [__meta_docker_container_name]
        regex: '.*_llama-agent_(\d+)'
        target_label: agent_id
        replacement: 'agent-${1}'
      # Add service labels
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      # Add container labels for better identification
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
        regex: '(.{12}).*'
        replacement: '${1}'
    scrape_interval: 5s  # More frequent for agent metrics
    metrics_path: /metrics
    scrape_timeout: 10s

  # MCP Gateway metrics
  - job_name: 'mcp-gateway'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 8001
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.compose.service=mcp-gateway"]
    relabel_configs:
      - source_labels: [__meta_docker_port_public]
        regex: '8001'
        action: keep
      - target_label: job
        replacement: 'mcp-gateway'
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
        regex: '(.{12}).*'
        replacement: '${1}'
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Cerebras Proxy metrics
  - job_name: 'cerebras-proxy'
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 8002
        refresh_interval: 15s
        filters:
          - name: label
            values: ["com.docker.compose.service=cerebras-proxy"]
    relabel_configs:
      - source_labels: [__meta_docker_port_public]
        regex: '8002'
        action: keep
      - target_label: job
        replacement: 'cerebras-proxy'
      - source_labels: [__meta_docker_container_label_com_docker_compose_service]
        target_label: service_name
      - source_labels: [__meta_docker_container_id]
        target_label: container_id
        regex: '(.{12}).*'
        replacement: '${1}'
    scrape_interval: 5s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Static configuration for services with known endpoints
  - job_name: 'ape-services-static'
    static_configs:
      - targets: 
          - 'mcp-gateway:8001'
          - 'cerebras-proxy:8002'
        labels:
          environment: 'ape-test'
    scrape_interval: 15s
    metrics_path: /metrics