global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'ape-load-test'
    environment: 'development'

rule_files:
  - "prometheus-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      # Add custom labels for APE services
      - source_labels: [container_label_com_docker_compose_service]
        target_label: ape_service
      - source_labels: [container_label_com_docker_compose_project]
        target_label: ape_project
      # Rename container name for clarity
      - source_labels: [name]
        regex: '/(.*)'
        target_label: container_name

  # Node Exporter for host system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    metrics_path: /metrics

  # APE Agent metrics (static configuration)
  - job_name: 'ape-agent'
    static_configs:
      - targets: ['test-final-fix-llama_agent-1:8000']
        labels:
          agent_id: 'agent-1'
          service_name: 'llama-agent'
          environment: 'ape-test'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # MCP Gateway metrics (static configuration)
  - job_name: 'mcp-gateway'
    static_configs:
      - targets: ['test-final-fix-mcp_gateway-1:8001']
        labels:
          service_name: 'mcp-gateway'
          environment: 'ape-test'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Cerebras Proxy metrics (static configuration)
  - job_name: 'cerebras-proxy'
    static_configs:
      - targets: ['test-final-fix-cerebras_proxy-1:8002']
        labels:
          service_name: 'cerebras-proxy'
          environment: 'ape-test'
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s

  # Static configuration for services with known endpoints
  - job_name: 'ape-services-static'
    static_configs:
      - targets: 
          - 'mcp-gateway:8001'
          - 'cerebras-proxy:8002'
        labels:
          environment: 'ape-test'
    scrape_interval: 15s
    metrics_path: /metrics